version: '3.8'

services:
  mongodb:
    image: mongo:4.4
    container_name: my-mongo-container
    ports:
      - "27017:27017"
    networks:
      - mongo_network
    volumes:
      - mongo_data:/data/db
    environment:
       MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
       MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  mongo-express:
    image: mongo-express
    container_name: mongo-express-container
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_BASICAUTH: false
    ports:
      - "8081:8081"
    networks:
      - mongo_network

networks:
  mongo_network:

volumes:
  mongo_data:

